# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: imageops.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'imageops.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eimageops.proto\x12\x08imageops\"\"\n\nAddRequest\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x17\n\x08\x41\x64\x64Reply\x12\x0b\n\x03sum\x18\x01 \x01(\x05\"\x1a\n\nImageBytes\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"*\n\tImageInfo\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\"\"\n\nVectorPair\x12\t\n\x01\x61\x18\x01 \x03(\x02\x12\t\n\x01\x62\x18\x02 \x03(\x02\"\x17\n\x08\x44otReply\x12\x0b\n\x03\x64ot\x18\x01 \x01(\x02\x32\xe2\x01\n\x08ImageOps\x12/\n\x03\x41\x64\x64\x12\x14.imageops.AddRequest\x1a\x12.imageops.AddReply\x12\x35\n\x08RawImage\x12\x14.imageops.ImageBytes\x1a\x13.imageops.ImageInfo\x12\x36\n\tJsonImage\x12\x14.imageops.ImageBytes\x1a\x13.imageops.ImageInfo\x12\x36\n\nDotProduct\x12\x14.imageops.VectorPair\x1a\x12.imageops.DotReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'imageops_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDREQUEST']._serialized_start=28
  _globals['_ADDREQUEST']._serialized_end=62
  _globals['_ADDREPLY']._serialized_start=64
  _globals['_ADDREPLY']._serialized_end=87
  _globals['_IMAGEBYTES']._serialized_start=89
  _globals['_IMAGEBYTES']._serialized_end=115
  _globals['_IMAGEINFO']._serialized_start=117
  _globals['_IMAGEINFO']._serialized_end=159
  _globals['_VECTORPAIR']._serialized_start=161
  _globals['_VECTORPAIR']._serialized_end=195
  _globals['_DOTREPLY']._serialized_start=197
  _globals['_DOTREPLY']._serialized_end=220
  _globals['_IMAGEOPS']._serialized_start=223
  _globals['_IMAGEOPS']._serialized_end=449
# @@protoc_insertion_point(module_scope)
