# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import imageops_pb2 as imageops__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in imageops_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ImageOpsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Add = channel.unary_unary(
                '/imageops.ImageOps/Add',
                request_serializer=imageops__pb2.AddRequest.SerializeToString,
                response_deserializer=imageops__pb2.AddReply.FromString,
                _registered_method=True)
        self.RawImage = channel.unary_unary(
                '/imageops.ImageOps/RawImage',
                request_serializer=imageops__pb2.ImageBytes.SerializeToString,
                response_deserializer=imageops__pb2.ImageInfo.FromString,
                _registered_method=True)
        self.JsonImage = channel.unary_unary(
                '/imageops.ImageOps/JsonImage',
                request_serializer=imageops__pb2.ImageBytes.SerializeToString,
                response_deserializer=imageops__pb2.ImageInfo.FromString,
                _registered_method=True)
        self.DotProduct = channel.unary_unary(
                '/imageops.ImageOps/DotProduct',
                request_serializer=imageops__pb2.VectorPair.SerializeToString,
                response_deserializer=imageops__pb2.DotReply.FromString,
                _registered_method=True)


class ImageOpsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Add(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RawImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JsonImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DotProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageOpsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Add': grpc.unary_unary_rpc_method_handler(
                    servicer.Add,
                    request_deserializer=imageops__pb2.AddRequest.FromString,
                    response_serializer=imageops__pb2.AddReply.SerializeToString,
            ),
            'RawImage': grpc.unary_unary_rpc_method_handler(
                    servicer.RawImage,
                    request_deserializer=imageops__pb2.ImageBytes.FromString,
                    response_serializer=imageops__pb2.ImageInfo.SerializeToString,
            ),
            'JsonImage': grpc.unary_unary_rpc_method_handler(
                    servicer.JsonImage,
                    request_deserializer=imageops__pb2.ImageBytes.FromString,
                    response_serializer=imageops__pb2.ImageInfo.SerializeToString,
            ),
            'DotProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.DotProduct,
                    request_deserializer=imageops__pb2.VectorPair.FromString,
                    response_serializer=imageops__pb2.DotReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'imageops.ImageOps', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('imageops.ImageOps', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ImageOps(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imageops.ImageOps/Add',
            imageops__pb2.AddRequest.SerializeToString,
            imageops__pb2.AddReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RawImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imageops.ImageOps/RawImage',
            imageops__pb2.ImageBytes.SerializeToString,
            imageops__pb2.ImageInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JsonImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imageops.ImageOps/JsonImage',
            imageops__pb2.ImageBytes.SerializeToString,
            imageops__pb2.ImageInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DotProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imageops.ImageOps/DotProduct',
            imageops__pb2.VectorPair.SerializeToString,
            imageops__pb2.DotReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
